### PR TITLE
Monkey-patching window instead of giving a full new instance

### PR DESCRIPTION
**Pull request by rgolea**
Hi there!

I see that this project is a dependency of swiper.js and I had an issue with Ionic because of swiper.js and angular universal. You can check the full issue right here: [#21138](https://github.com/ionic-team/ionic/issues/21138).

It seems like somewhere along the lines, `window` is defined for SSR and swiper depends on this repo to get the screen size. Since there might already be a partially injected window, I thought that the best course of action is, instead of using one or the other, it should be monkey-patching the values so any other values can be added to another partial window interface.

I also had to switch to webpack/typescript. Had some issues with the version of gulp that it was used here. This gives also some benefits of having type safety when using the library.

Hope it helps and if this is not the way to fix the issue, please help me into pointing me in the right direction. Thank you!

### CODE REVIEW

**Comment by nolimits4web** [comment]
Thanks! But i can accept this PR for few reasons:
- we don't need web pack here, it doubles the output dist files with a lot of "garbage"
- we still need `esm` modules to be there, why they removed?

Can you change it to modifying only `src` files? If not, i can merge it manually this weekend then

**Comment by rgolea** [comment]
@nolimits4web To answer your questions and issues in order:

  * I know there is no need for webpack but I couldn't make gulp work under any circumstances. Also, I fear some ES6 and backward compatibility issues (that's why i added typescript)
  * I don't really know how to change to target `esm`, maybe it's something regarding the `ts-loader` options and adding another entrypoint? I'm not really sure on the difference as well.
  * I'm pretty sure we can add `.d.ts` files to the project and it will allow the interface to display all usages of future implemented methods.

I can definitely change the PR to only change the few parts but I cannot even test nor build the project and I'm afraid I might break something. Ping me back as soon as you can.

Thanks

**Comment by nolimits4web** [comment]
Ok, can you then just keep changes in `src` files, e.g. monkey patching itself + keep in TypeScript, and i will update the build process and rest of the stuff

**Comment by rgolea** [comment]
You're a life saver! I will do it right now.

**Comment by rgolea** [comment]
@nolimits4web do you want me to leave the `tsconfig` base file?

**Comment by nolimits4web** [comment]
Yes, keep it, I’ll tweak it if needed

**Comment by rgolea** [comment]
@nolimits4web right now it builds in the `build` folder. You can also extends the base `tsconfig` file and have running multiple configs (like the output directory, modules usage like commonjs, etc). If anything, ping me and I will keep looking into it.

**Comment by nolimits4web** [comment]
@rgolea i just released sir-window 2.x beta, can you try if it works for you:
```
npm i ssr-window@beta
```

**Comment by rgolea** [comment]
@nolimits4web I'll try it this weekend. Thank you sooo much!

**Comment by rgolea** [comment]
@nolimits4web since you are doing the `extend` recursively, you are not null checking:
https://github.com/nolimits4web/ssr-window/blob/30be0343bab593bbf0fa63b13f98446bc0eeddd1/src/extend.ts#L2

I think you should do
```
function extend(target: any = {}, src: any = {}){
```

**Pull request merged**
