### PR TITLE
SSR crashes on swiper/ionic.

### PR DESCRIPTION
**Pull request by rgolea**
@nolimits4web Seems like the previous version would crash because it doesn't do null checking when doing deep extension. Gives an error when reassigning properties.

I get `TypeError: Cannot read property 'blur' of null`. I could only allow it to work by changing back the `extend` function.

You can test this functionality with this demo repo: https://github.com/rgolea/ionic-ssr-errors

You can run `npm run prerender` and see the error. When changing the following files with the bundled version (ionic includes the bundled version of swiper), you can test different solutions. I, for one, the only one that I found it works is this one.

Files:
```
./node_modules/@ionic/core/hydrate/index.js
./node_modules/@ionic/core/dist/ionic/swiper/swiper.bundle.js
./node_modules/@ionic/core/dist/esm-es5/swiper.bundle-f564f87c.js
./node_modules/@ionic/core/dist/esm/swiper.bundle-f564f87c.js
./node_modules/@ionic/core/dist/collection/components/slides/swiper/swiper.bundle.js
./node_modules/@ionic/core/dist/cjs/swiper.bundle-aa509bdb.js
```
Cheers and thanks again for your interest!

Note: on Ionic/Angular you are rendering with [domino](https://github.com/fgnass/domino), which doesn't have the `window.screen` implemented. In order to do a proper and deep extend, you need to do check on the target, it's `__proto__` and it's descriptor.

In other tests I did, I got to this extend function, which doesn't fully work:
```
function isWritable(target, key){
  const descriptor = (target && target.__proto__) ? Object.getOwnPropertyDescriptor(target.__proto__, key) : Object.getOwnPropertyDescriptor(target, key)
  return (!descriptor || descriptor.writable || descriptor.set)
}

/* eslint-disable no-param-reassign */
function extend(target, src) {
  if (target === void 0) { target = {}; }
  if (src === void 0) { src = {}; }
  Object.keys(src).filter(function(key){
    return isWritable(target, key);
  }).forEach(function (key) {
      if (typeof target[key] === 'undefined'){
          target[key] = src[key];
      } else if(
        typeof src[key] === 'object' &&
        src[key].constructor === Object &&
        Object.keys(src[key]).length > 0
      ){
        target[key] = extend(target[key], src[key]);
      }
  });
  return target;
}
```
Since I don't think this library means to be a full spec polyfill, I would just replace items on `window` and `document` and would just do a replacement and not a deep copy.

### CODE REVIEW

**Comment by nolimits4web** [comment]
In this repo https://github.com/rgolea/ionic-ssr-errors i see it still uses old version, as Swiper + SSR are bundled into ionic, not as dependencies

**Comment by rgolea** [comment]
@nolimits4web  Yes, I had to add the changes manually and replace the files in order to make it work and test. There is an issue open where they said they will change the bundle when this will open.

**Comment by nolimits4web** [comment]
Pushed fix with corrected extend method, and released 2.0.0-beta.8 + added simple test for domino https://github.com/nolimits4web/ssr-window/blob/master/test/test-domino.js, works good now

**Comment by rgolea** [comment]
@nolimits4web this works perfectly! I think it's safe to add it now as v2 and maybe change it in swiper?

**Comment by nolimits4web** [comment]
Awesome, will update in Swiper with its next update anytime soon

**Pull request closed without merging**
